"""product content columns

Revision ID: 304c5aacb3dd
Revises: 73e3b50d9945
Create Date: 2026-07-03 13:34:51.951169
"""
from alembic import op
import sqlalchemy as sa


revision = '304c5aacb3dd'
down_revision = '73e3b50d9945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('short_description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('seo_title', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('seo_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'seo_description')
    op.drop_column('products', 'seo_title')
    op.drop_column('products', 'short_description')
    # ### end Alembic commands ###
