"""drop speculative product columns

Revision ID: 73e3b50d9945
Revises: fdcf336ff3ed
Create Date: 2026-07-02 22:29:43.609515
"""

from alembic import op
import sqlalchemy as sa


revision = "73e3b50d9945"
down_revision = "fdcf336ff3ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("products_parent_id_fkey"), "products", type_="foreignkey")
    op.drop_column("products", "parent_id")
    op.drop_column("products", "seo_description")
    op.drop_column("products", "short_description")
    op.drop_column("products", "seo_title")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("seo_title", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column(
        "products", sa.Column("short_description", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "products", sa.Column("seo_description", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "products", sa.Column("parent_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        op.f("products_parent_id_fkey"), "products", "products", ["parent_id"], ["id"]
    )
    # ### end Alembic commands ###
