/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Product */
        patch: operations["update_product_api_products__product_id__patch"];
        trace?: never;
    };
    "/api/products/{product_id}/repull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Repull Product */
        post: operations["repull_product_api_products__product_id__repull_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pricing/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_api_pricing_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pricing/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Rule */
        put: operations["update_rule_api_pricing_rules__rule_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Export */
        post: operations["trigger_export_api_jobs_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/sync/{supplier_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Sync */
        post: operations["trigger_sync_api_jobs_sync__supplier_code__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        /** Create Category */
        post: operations["create_category_api_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mappings */
        get: operations["list_mappings_api_categories_mappings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/mappings/{mapping_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Mapping */
        patch: operations["update_mapping_api_categories_mappings__mapping_id__patch"];
        trace?: never;
    };
    "/api/categories/{category_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Category */
        delete: operations["delete_category_api_categories__category_id__delete"];
        options?: never;
        head?: never;
        /** Update Category */
        patch: operations["update_category_api_categories__category_id__patch"];
        trace?: never;
    };
    "/api/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suppliers */
        get: operations["list_suppliers_api_suppliers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feeds */
        get: operations["list_feeds_api_feeds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Feed */
        patch: operations["update_feed_api_feeds__kind__patch"];
        trace?: never;
    };
    "/api/feeds/{kind}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Feed */
        post: operations["run_feed_api_feeds__kind__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spa */
        get: operations["spa__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CategoryCreate */
        CategoryCreate: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: number | null;
        };
        /** CategoryMappingOut */
        CategoryMappingOut: {
            /** Id */
            id: number;
            /** Supplier Id */
            supplier_id: number;
            /** Supplier Path */
            supplier_path: string;
            /** Category Id */
            category_id: number;
        };
        /** CategoryMappingUpdate */
        CategoryMappingUpdate: {
            /** Category Id */
            category_id: number;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Id */
            id: number;
            /** Parent Id */
            parent_id: number | null;
            /** Name */
            name: string;
            /** Seo Title */
            seo_title: string | null;
            /** Seo Description */
            seo_description: string | null;
            /** Upgates Code */
            upgates_code: string | null;
        };
        /** CategoryUpdate */
        CategoryUpdate: {
            /** Name */
            name?: string | null;
            /** Parent Id */
            parent_id?: number | null;
            /** Seo Title */
            seo_title?: string | null;
            /** Seo Description */
            seo_description?: string | null;
        };
        /** FeedConfigOut */
        FeedConfigOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Feed Url */
            feed_url: string | null;
            /** Update Whitelist */
            update_whitelist: string[];
            /** Last Run At */
            last_run_at: string | null;
            /**
             * Available Fields
             * @default []
             */
            available_fields: string[];
        };
        /** FeedConfigUpdate */
        FeedConfigUpdate: {
            /** Feed Url */
            feed_url?: string | null;
            /** Update Whitelist */
            update_whitelist?: string[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobRunOut */
        JobRunOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            /** Error */
            error: string | null;
        };
        /** MarginRuleOut */
        MarginRuleOut: {
            /** Id */
            id: number;
            /** Scope */
            scope: string;
            /** Match Value */
            match_value: string | null;
            /** Margin Pct */
            margin_pct: string;
        };
        /** MarginRuleUpdate */
        MarginRuleUpdate: {
            /** Margin Pct */
            margin_pct: number | string;
        };
        /** ProductCategoryIO */
        ProductCategoryIO: {
            /** Category Id */
            category_id: number;
            /** Primary Yn */
            primary_yn: boolean;
        };
        /** ProductDetailOut */
        ProductDetailOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Supplier Id */
            supplier_id: number | null;
            /** Ean */
            ean: string | null;
            /** Manufacturer */
            manufacturer: string | null;
            /** Title */
            title: string | null;
            /** Short Description */
            short_description: string | null;
            /** Long Description */
            long_description: string | null;
            /** Seo Title */
            seo_title: string | null;
            /** Seo Description */
            seo_description: string | null;
            /** Url Slug */
            url_slug: string | null;
            /** Stock */
            stock: number | null;
            /** Weight */
            weight: number | null;
            /** Availability */
            availability: string | null;
            /** Active */
            active: boolean;
            /** Price Purchase */
            price_purchase: string | null;
            /** Coefficient */
            coefficient: string;
            /** Margin Pct */
            margin_pct: string | null;
            /** Note */
            note: string | null;
            /** Sale Price */
            sale_price?: string | null;
            /**
             * Params
             * @default []
             */
            params: components["schemas"]["ProductParamIO"][];
            /**
             * Images
             * @default []
             */
            images: components["schemas"]["ProductImageIO"][];
            /**
             * Categories
             * @default []
             */
            categories: components["schemas"]["ProductCategoryIO"][];
        };
        /** ProductImageIO */
        ProductImageIO: {
            /** Url */
            url: string;
            /** Alt */
            alt: string | null;
            /** Ord */
            ord: number;
        };
        /** ProductListOut */
        ProductListOut: {
            /** Items */
            items: components["schemas"]["ProductOut"][];
            /** Total */
            total: number;
        };
        /** ProductOut */
        ProductOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Supplier Id */
            supplier_id: number | null;
            /** Ean */
            ean: string | null;
            /** Manufacturer */
            manufacturer: string | null;
            /** Title */
            title: string | null;
            /** Short Description */
            short_description: string | null;
            /** Long Description */
            long_description: string | null;
            /** Seo Title */
            seo_title: string | null;
            /** Seo Description */
            seo_description: string | null;
            /** Url Slug */
            url_slug: string | null;
            /** Stock */
            stock: number | null;
            /** Weight */
            weight: number | null;
            /** Availability */
            availability: string | null;
            /** Active */
            active: boolean;
            /** Price Purchase */
            price_purchase: string | null;
            /** Coefficient */
            coefficient: string;
            /** Margin Pct */
            margin_pct: string | null;
            /** Note */
            note: string | null;
            /** Sale Price */
            sale_price?: string | null;
        };
        /** ProductParamIO */
        ProductParamIO: {
            /** Name */
            name: string;
            /** Value */
            value: string | null;
            /** Ord */
            ord: number;
        };
        /**
         * ProductUpdate
         * @description Owner-editable fields only. Supplier-owned fields (stock, price_purchase, ...) are not here.
         */
        ProductUpdate: {
            /** Title */
            title?: string | null;
            /** Short Description */
            short_description?: string | null;
            /** Long Description */
            long_description?: string | null;
            /** Seo Title */
            seo_title?: string | null;
            /** Seo Description */
            seo_description?: string | null;
            /** Url Slug */
            url_slug?: string | null;
            /** Active */
            active?: boolean | null;
            /** Coefficient */
            coefficient?: number | string | null;
            /** Margin Pct */
            margin_pct?: number | string | null;
            /** Note */
            note?: string | null;
            /** Params */
            params?: components["schemas"]["ProductParamIO"][] | null;
            /** Images */
            images?: components["schemas"]["ProductImageIO"][] | null;
            /** Categories */
            categories?: components["schemas"]["ProductCategoryIO"][] | null;
        };
        /** SupplierOut */
        SupplierOut: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_products_api_products_get: {
        parameters: {
            query?: {
                q?: string | null;
                filter?: string[];
                sort?: string | null;
                overrides?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repull_product_api_products__product_id__repull_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_pricing_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarginRuleOut"][];
                };
            };
        };
    };
    update_rule_api_pricing_rules__rule_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarginRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarginRuleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                kind?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_export_api_jobs_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    trigger_sync_api_jobs_sync__supplier_code__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supplier_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    create_category_api_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mappings_api_categories_mappings_get: {
        parameters: {
            query?: {
                category_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryMappingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_mapping_api_categories_mappings__mapping_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mapping_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryMappingUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryMappingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_category_api_categories__category_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_category_api_categories__category_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_suppliers_api_suppliers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierOut"][];
                };
            };
        };
    };
    list_feeds_api_feeds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedConfigOut"][];
                };
            };
        };
    };
    update_feed_api_feeds__kind__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedConfigUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_feed_api_feeds__kind__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    spa__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
